### ISSUE TITLE
Current requirements.txt leads to pip conflict

### ISSUE THREAD

**Issue by mo-st** [shangar21/anime_upscaler#7] opened 2024-03-21 08:54 UTC
Install with `pip install -r requirements.txt` leads to the following dependency conflict:

```
The conflict is caused by:
    The user requested Pillow==10.1.0
    basicsr 1.4.2 depends on Pillow
    image-slicer 2.1.1 depends on Pillow==7.2.0
```
I will try to run with removing the version specification for pillow entirely and update this issue after testing it.
Cheers and thanks for your scripts!

**Comment by mo-st** [comment] 2024-03-21 09:02
Update: doesn't seem to work, neither does setting version `==7.2.0`. Don't have time to look into the specifics atm, building wheel fails though. Will update if I find the time.

**Comment by shangar21** [comment] 2024-03-22 15:03
Yeah I think the problem is with image_slicer, I will eventually write the slicer myself but if you want to install it, try to git clone the source repo and build with  `pip install -e .` instead: https://github.com/samdobson/image_slicer (assuming you have the rest of the dependencies installed).

**Comment by sampanes** [comment] 2024-05-18 17:22
I have a venv and I have several repos in it, the third of which is now image_slicer,
I went into that directory and did `pip install -e .` and got image-slicer, 
then pillow wasn't working so I went back and did pip install Pillow==10.1.0, 
then ran the frame_esrgan.py on an image and got decent output (disney movie frame, not anime) so I think this is the right answer

**Comment by shangar21** [comment] 2024-05-21 19:28
Awesome. closing the issue now then

**Closed as completed by shangar21** 2024-05-21 19:28 UTC
